const maceraSeviyeleri = [
    { level: 1, emoji: "🍎", ad_key: "level1_ad", kategori: "meyveler", hedefKelime: 5, odul: 100 },
    { level: 2, emoji: "🏛️", ad_key: "level2_ad", kategori: "sehirler", hedefKelime: 5, odul: 125 },
    { level: 3, emoji: "🦁", ad_key: "level3_ad", kategori: "hayvanlar", hedefKelime: 5, odul: 150 },
    { level: 4, emoji: "🚗", ad_key: "level4_yeni_ad", kategori: "tasitlar", hedefKelime: 6, odul: 160 },
    { level: 5, emoji: "🍔", ad_key: "level4_ad", kategori: "yemek", hedefKelime: 6, odul: 175 },
    { level: 6, emoji: "🌎", ad_key: "level5_ad", kategori: "ulkeler", hedefKelime: 7, odul: 200 },
    { level: 7, emoji: "🧠", ad_key: "level6_ad", kategori: "sehirler", hedefKelime: 3, odul: 300, kelimeFiltresi: kelime => kelime.replace(/\s/g, '').length >= 10 },
    { level: 8, emoji: "🌸", ad_key: "level8_yeni_ad", kategori: "bitkiler", hedefKelime: 7, odul: 215 },
    { level: 9, emoji: "🛠️", ad_key: "level7_ad", kategori: "meslek", hedefKelime: 7, odul: 225 },
    { level: 10, emoji: "🛋️", ad_key: "level8_ad", kategori: "esya", hedefKelime: 8, odul: 250 },
    { level: 11, emoji: "🍇", ad_key: "level9_ad", kategori: "meyveler", hedefKelime: 7, odul: 250, kelimeFiltresi: kelime => kelime.length >= 7 },
    { level: 12, emoji: "🏀", ad_key: "level12_yeni_ad", kategori: "spor", hedefKelime: 8, odul: 265 },
    { level: 13, emoji: "🦓", ad_key: "level10_ad", kategori: "hayvanlar", hedefKelime: 8, odul: 275 },
    { level: 14, emoji: "🍕", ad_key: "level11_ad", kategori: "yemek", hedefKelime: 8, odul: 300 },
    { level: 15, emoji: "🏰", ad_key: "level12_ad", kategori: "ulkeler", hedefKelime: 8, odul: 325, kelimeFiltresi: kelime => kelime.length <= 8 },
    { level: 16, emoji: "🪐", ad_key: "level16_yeni_ad", kategori: "uzay", hedefKelime: 9, odul: 340 },
    { level: 17, emoji: "🖋️", ad_key: "level13_ad", kategori: "esya", hedefKelime: 10, odul: 350 },
    { level: 18, emoji: "🩺", ad_key: "level14_ad", kategori: "meslek", hedefKelime: 10, odul: 400 },
    { level: 19, emoji: "🏆", ad_key: "level15_ad", kategori: "sehirler", hedefKelime: 3, odul: 750, kelimeFiltresi: kelime => kelime.length >= 12 },
];